version: '3'
services: 
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
        - ENV=PRODUCTION
        - DEFAULT_ADMIN_ACCOUNT=areis
        - DEFAULT_ADMIN_NAME=Alexis Reis
        - DEFAULT_ADMIN_MAIL=alexis.reis@mail.com
    volumes:
      - ./db:/app/db